name: Keep Alive
on:
  schedule:
    - cron: 0 0 * * *

permissions:
  actions: write

jobs:
  cronjob-based-github-action:
    name: Keep Alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          workflow_files: xyplorer.yml
          time_elapsed: 0