name: SideQuest.EasyInstaller

on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

env:
  owner: SideQuestVR
  repository: EasyInstallerReleases
  packageId: SideQuestVR.SideQuestEasyInstaller
  wingetCreateUrl: https://aka.ms/wingetcreate/latest

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get Latest Release
        shell: pwsh
        run: |
          Install-Module Microsoft.WinGet.Client
          Install-Module PowerShellForGitHub

          # Get the current Winget version of the package
          $wingetVersion = Find-WinGetPackage -Id ${{env.packageId}} | `
              Select-Object -ExpandProperty version

          $release = Get-GitHubRelease `
              -OwnerName ${{env.owner}} `
              -RepositoryName ${{env.repository}} `
              -Latest
          $version = $release.tag_name -replace 'v', ''

          if ($version -eq $wingetVersion) {
            Write-Host "Released Version ($version) == Winget Version ($wingetVersion)...Exiting"
            return
          }

          $downloadUrl = $release.assets | `
            Where-Object name -Match 'SideQuest-Setup-.*-x64-win.exe$' | `
            Select-Object -ExpandProperty browser_download_url

          Invoke-WebRequest ${{env.wingetCreateUrl}} -OutFile wingetcreate.exe

          .\wingetcreate.exe update ${{env.packageId}} `
            -urls '$downloadUrl' '$downloadUrl' `
            --version ${{version}} `
            --submit `
            --token ${{secrets.PublicToken}}
