name: XYplorer

on:
  schedule:
  - cron: 0 0 * * *
  push:
    paths:
      - .github/workflows/xyplorer.yml
      - ./Scripts/xyplorer.ps1
      - ./Common
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-to-winget:
    name: Publish to WinGet
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install WinGet
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install WinGetCreate
        run: winget install wingetcreate --disable-interactivity --accept-source-agreements

      - name: Get Latest Release
        shell: pwsh
        run: |
          ./Scripts/xyplorer.portable.ps1 `
            -gitHubAccessToken ${{secrets.AccessToken}} `
            -skipSubmit
